### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: errors.map is not a function

### ISSUE THREAD

**Issue by MichalBryxi** [lifeart/ember-language-server#181]
When I tried to bump `"ember-template-lint": "v3.0.0-beta.0",` I started getting following:

```
(node:48145) UnhandledPromiseRejectionWarning: TypeError: errors.map is not a function
    at TemplateLinter.<anonymous> (/Users/michal/.vscode/extensions/lifeart.vscode-ember-unstable-1.6.0/node_modules/@emberwatch/ember-language-server/lib/template-linter.js:80:40)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/michal/.vscode/extensions/lifeart.vscode-ember-unstable-1.6.0/node_modules/@emberwatch/ember-language-server/lib/template-linter.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:48145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:48145) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:48145) UnhandledPromiseRejectionWarning: TypeError: errors.map is not a function
    at TemplateLinter.<anonymous> (/Users/michal/.vscode/extensions/lifeart.vscode-ember-unstable-1.6.0/node_modules/@emberwatch/ember-language-server/lib/template-linter.js:80:40)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/michal/.vscode/extensions/lifeart.vscode-ember-unstable-1.6.0/node_modules/@emberwatch/ember-language-server/lib/template-linter.js:4:58)
(node:48145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:48145) UnhandledPromiseRejectionWarning: TypeError: errors.map is not a function
    at TemplateLinter.<anonymous> (/Users/michal/.vscode/extensions/lifeart.vscode-ember-unstable-1.6.0/node_modules/@emberwatch/ember-language-server/lib/template-linter.js:80:40)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/michal/.vscode/extensions/lifeart.vscode-ember-unstable-1.6.0/node_modules/@emberwatch/ember-language-server/lib/template-linter.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:48145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by lifeart** [comment]
Related code https://github.com/lifeart/ember-language-server/blob/component-context-info-origin/src/template-linter.ts#L119

**Comment by lifeart** [comment]
Template-lint code: https://github.com/ember-template-lint/ember-template-lint/blob/next/lib/linter.js#L372

**Comment by lifeart** [comment]
Verify method now asynchronous

**Comment by lifeart** [comment]
@MichalBryxi could you try `lifeart.vscode-ember-unstable@2.0.0`?

**Comment by MichalBryxi** [comment]
Installed:
 - `"ember-template-lint": "v3.0.0-beta.0",`
 - `lifeart.vscode-ember-unstable@2.0.0`

And it works! \o/ Thank you.

![Screenshot 2021-01-17 at 12 28 30](https://user-images.githubusercontent.com/847473/104842869-8b0fd300-58bf-11eb-9716-0e5d4790d120.png)
